# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: web.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='web.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\tweb.proto\"+\n\x08WebOrder\x12\x0f\n\x07orderID\x18\x01 \x02(\x03\x12\x0e\n\x06userID\x18\x02 \x02(\x03\"?\n\x0fWebPurchaseMore\x12\r\n\x05whnum\x18\x01 \x02(\x05\x12\x0e\n\x06itemId\x18\x02 \x02(\x03\x12\r\n\x05\x63ount\x18\x03 \x02(\x05\"C\n\x0eWebPurchaseNew\x12\r\n\x05whnum\x18\x01 \x02(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x02(\t\x12\r\n\x05\x63ount\x18\x03 \x02(\x05\"w\n\x0bWebCommands\x12\x19\n\x06orders\x18\x01 \x03(\x0b\x32\t.WebOrder\x12\'\n\rpurchaseMores\x18\x02 \x03(\x0b\x32\x10.WebPurchaseMore\x12$\n\x0bnewProducts\x18\x03 \x03(\x0b\x32\x0f.WebPurchaseNew')
)




_WEBORDER = _descriptor.Descriptor(
  name='WebOrder',
  full_name='WebOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderID', full_name='WebOrder.orderID', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userID', full_name='WebOrder.userID', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=56,
)


_WEBPURCHASEMORE = _descriptor.Descriptor(
  name='WebPurchaseMore',
  full_name='WebPurchaseMore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='whnum', full_name='WebPurchaseMore.whnum', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='itemId', full_name='WebPurchaseMore.itemId', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='WebPurchaseMore.count', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=121,
)


_WEBPURCHASENEW = _descriptor.Descriptor(
  name='WebPurchaseNew',
  full_name='WebPurchaseNew',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='whnum', full_name='WebPurchaseNew.whnum', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='WebPurchaseNew.description', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='WebPurchaseNew.count', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=190,
)


_WEBCOMMANDS = _descriptor.Descriptor(
  name='WebCommands',
  full_name='WebCommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orders', full_name='WebCommands.orders', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='purchaseMores', full_name='WebCommands.purchaseMores', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='newProducts', full_name='WebCommands.newProducts', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=311,
)

_WEBCOMMANDS.fields_by_name['orders'].message_type = _WEBORDER
_WEBCOMMANDS.fields_by_name['purchaseMores'].message_type = _WEBPURCHASEMORE
_WEBCOMMANDS.fields_by_name['newProducts'].message_type = _WEBPURCHASENEW
DESCRIPTOR.message_types_by_name['WebOrder'] = _WEBORDER
DESCRIPTOR.message_types_by_name['WebPurchaseMore'] = _WEBPURCHASEMORE
DESCRIPTOR.message_types_by_name['WebPurchaseNew'] = _WEBPURCHASENEW
DESCRIPTOR.message_types_by_name['WebCommands'] = _WEBCOMMANDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WebOrder = _reflection.GeneratedProtocolMessageType('WebOrder', (_message.Message,), dict(
  DESCRIPTOR = _WEBORDER,
  __module__ = 'web_pb2'
  # @@protoc_insertion_point(class_scope:WebOrder)
  ))
_sym_db.RegisterMessage(WebOrder)

WebPurchaseMore = _reflection.GeneratedProtocolMessageType('WebPurchaseMore', (_message.Message,), dict(
  DESCRIPTOR = _WEBPURCHASEMORE,
  __module__ = 'web_pb2'
  # @@protoc_insertion_point(class_scope:WebPurchaseMore)
  ))
_sym_db.RegisterMessage(WebPurchaseMore)

WebPurchaseNew = _reflection.GeneratedProtocolMessageType('WebPurchaseNew', (_message.Message,), dict(
  DESCRIPTOR = _WEBPURCHASENEW,
  __module__ = 'web_pb2'
  # @@protoc_insertion_point(class_scope:WebPurchaseNew)
  ))
_sym_db.RegisterMessage(WebPurchaseNew)

WebCommands = _reflection.GeneratedProtocolMessageType('WebCommands', (_message.Message,), dict(
  DESCRIPTOR = _WEBCOMMANDS,
  __module__ = 'web_pb2'
  # @@protoc_insertion_point(class_scope:WebCommands)
  ))
_sym_db.RegisterMessage(WebCommands)


# @@protoc_insertion_point(module_scope)
